create or replace view &pfx.obj as
select
   &low obj.owner       &wol&ci   own,
   &low obj.object_name &wol&ci   obj,
   decode(obj.object_type,
       'CLUSTER'               , 'clus'   ,
       'CONSUMER GROUP'        , 'congrp' ,
       'CONTAINER'             , 'cont'   ,
       'CONTEXT'               , 'ctx'    ,
       'DATABASE LINK'         , 'dblink' ,
       'DESTINATION'           , 'dest'   ,
       'DIRECTORY'             , 'dir'    ,
       'EDITION'               , 'edn'    ,
       'EVALUATION CONTEXT'    , 'evalctx',
       'FUNCTION'              , 'func'   ,
       'INDEX'                 , 'ind'    ,
       'INDEX PARTITION'       , 'indpart',
       'INDEXTYPE'             , 'indtyp' ,
       'JAVA CLASS'            , 'javcls' ,
       'JAVA DATA'             , 'jdat'   ,
       'JAVA RESOURCE'         , 'javres' ,
       'JAVA SOURCE'           , 'javsrc' ,
       'JOB'                   , 'job'    ,
       'JOB CLASS'             , 'jobcls' ,
       'LIBRARY'               , 'lib'    ,
       'LOB'                   , 'lob'    ,
       'LOB PARTITION'         , 'lobpart',
       'OPERATOR'              , 'opr'    ,
       'PACKAGE'               , 'pkg'    ,
       'PACKAGE BODY'          , 'pkb'    ,
       'PROGRAM'               , 'prog'   ,
       'PROCEDURE'             , 'proc'   ,
       'QUEUE'                 , 'que'    ,
       'RESOURCE PLAN'         , 'rplan'  ,
       'RULE'                  , 'rule'   ,
       'RULE SET'              , 'rset'   ,
       'SCHEDULE'              , 'sched'  ,
       'SCHEDULER GROUP'       , 'schgrp' ,
       'SEQUENCE'              , 'seq'    ,
       'SYNONYM'               , 'syn'    ,
       'TABLE'                 , 'tab'    ,
       'TABLE PARTITION'       , 'tabpart',
       'TABLE SUBPARTITION'    , 'tabsubp',
       'TRIGGER'               , 'trg'    ,
       'TYPE'                  , 'typ'    ,
       'TYPE BODY'             , 'tpb'    ,
       'UNDEFINED'             , 'undef'  ,
       'UNIFIED AUDIT POLICY'  , 'uap'    ,
       'VIEW'                  , 'view'   ,
       'WINDOW'                , 'win'    ,
       'XML SCHEMA'            , 'xmlsch' ,
       lower(obj.object_type)
   )                                               typ,
   obj.created,
   obj.last_ddl_time,
   to_date(obj.timestamp, 'yyyy-mm-dd:hh24:mi:ss') ts,
   &low obj.status        &wol  &ci                st,
   &low oracle_maintained &wol                     ora,
   obj.object_id                                   id,
   lower('drop ' ||
      case when obj.object_type  = 'DATABASE LINK' and obj.owner = 'PUBLIC' then 'public ' end ||
      obj.object_type || ' ' ||
      case when obj.object_type != 'DATABASE LINK'                          then obj.owner || '.' end ||
      obj.object_name || ';') stmt_drop
from
   dba_objects obj;
